---
title: Cramer's Rule - Examples for 2x2, 3x3, and 4x4 Systems
jupyter: python3
---

Cramer's rule is used only when the number of equations is equal to the number of unknowns. In other words, the coefficient matrix must be a square matrix.

**These formulas are used only** when the **determinant** of the coefficient matrix is **non-zero**. Otherwise, the system of equations is either inconsistent or indeterminate.

## 2x2 System of Equations

Consider a system of two equations with two unknowns:

$$
\begin{cases}
a_{11}x_1 + a_{12}x_2 = b_1 \\
a_{21}x_1 + a_{22}x_2 = b_2
\end{cases}
$$

Cramer's rule for the unknowns $ x_1 $ and $ x_2 $ is as follows:

$$
x_1 = \frac{\det(A_1)}{\det(A)} \quad \text{and} \quad x_2 = \frac{\det(A_2)}{\det(A)}
$$

Where:

$$
\det(A) = 
\begin{vmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{vmatrix} 
= a_{11}a_{22} - a_{12}a_{21}
$$

$$
\det(A_1) = 
\begin{vmatrix}
b_1 & a_{12} \\
b_2 & a_{22}
\end{vmatrix} 
= b_1a_{22} - a_{12}b_2
$$

$$
\det(A_2) = 
\begin{vmatrix}
a_{11} & b_1 \\
a_{21} & b_2
\end{vmatrix} 
= a_{11}b_2 - b_1a_{21}
$$

## 3x3 System of Equations

Consider a system of three equations with three unknowns:

$$
\begin{cases}
a_{11}x_1 + a_{12}x_2 + a_{13}x_3 = b_1 \\
a_{21}x_1 + a_{22}x_2 + a_{23}x_3 = b_2 \\
a_{31}x_1 + a_{32}x_2 + a_{33}x_3 = b_3
\end{cases}
$$

Cramer's rule for $ x_1 $, $ x_2 $, and $ x_3 $:

$$
x_1 = \frac{\det(A_1)}{\det(A)} \quad x_2 = \frac{\det(A_2)}{\det(A)} \quad x_3 = \frac{\det(A_3)}{\det(A)}
$$

Where:

$$
\det(A) = 
\begin{vmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{vmatrix}
$$

$$
\det(A_1) = 
\begin{vmatrix}
b_1 & a_{12} & a_{13} \\
b_2 & a_{22} & a_{23} \\
b_3 & a_{32} & a_{33}
\end{vmatrix}
$$

$$
\det(A_2) = 
\begin{vmatrix}
a_{11} & b_1 & a_{13} \\
a_{21} & b_2 & a_{23} \\
a_{31} & b_3 & a_{33}
\end{vmatrix}
$$

$$
\det(A_3) = 
\begin{vmatrix}
a_{11} & a_{12} & b_1 \\
a_{21} & a_{22} & b_2 \\
a_{31} & a_{32} & b_3
\end{vmatrix}
$$

## 4x4 System of Equations

Consider a system of four equations with four unknowns:

$$
\begin{cases}
a_{11}x_1 + a_{12}x_2 + a_{13}x_3 + a_{14}x_4 = b_1 \\
a_{21}x_1 + a_{22}x_2 + a_{23}x_3 + a_{24}x_4 = b_2 \\
a_{31}x_1 + a_{32}x_2 + a_{33}x_3 + a_{34}x_4 = b_3 \\
a_{41}x_1 + a_{42}x_2 + a_{43}x_3 + a_{44}x_4 = b_4
\end{cases}
$$

Cramer's rule for $ x_1 $, $ x_2 $, $ x_3 $, and $ x_4 $:

$$
x_1 = \frac{\det(A_1)}{\det(A)} \quad x_2 = \frac{\det(A_2)}{\det(A)} \quad x_3 = \frac{\det(A_3)}{\det(A)} \quad x_4 = \frac{\det(A_4)}{\det(A)}
$$

Where:

$$
\det(A) = 
\begin{vmatrix}
a_{11} & a_{12} & a_{13} & a_{14} \\
a_{21} & a_{22} & a_{23} & a_{24} \\
a_{31} & a_{32} & a_{33} & a_{34} \\
a_{41} & a_{42} & a_{43} & a_{44}
\end{vmatrix}
$$

$$
\det(A_1) = 
\begin{vmatrix}
b_1 & a_{12} & a_{13} & a_{14} \\
b_2 & a_{22} & a_{23} & a_{24} \\
b_3 & a_{32} & a_{33} & a_{34} \\
b_4 & a_{42} & a_{43} & a_{44}
\end{vmatrix}
$$

$$
\det(A_2) = 
\begin{vmatrix}
a_{11} & b_1 & a_{13} & a_{14} \\
a_{21} & b_2 & a_{23} & a_{24} \\
a_{31} & b_3 & a_{33} & a_{34} \\
a_{41} & b_4 & a_{43} & a_{44}
\end{vmatrix}
$$

$$
\det(A_3) = 
\begin{vmatrix}
a_{11} & a_{12} & b_1 & a_{14} \\
a_{21} & a_{22} & b_2 & a_{24} \\
a_{31} & a_{32} & b_3 & a_{34} \\
a_{41} & a_{42} & b_4 & a_{44}
\end{vmatrix}
$$

$$
\det(A_4) = 
\begin{vmatrix}
a_{11} & a_{12} & a_{13} & b_1 \\
a_{21} & a_{22} & a_{23} & b_2 \\
a_{31} & a_{32} & a_{33} & b_3 \\
a_{41} & a_{42} & a_{43} & b_4
\end{vmatrix}
$$

## Example

```{python}
import sympy as sp

# Define symbols
x, y, z = sp.symbols('x y z')

# Define the system of equations
eq1 = sp.Eq(2*x + 3*y + z, 1)
eq2 = sp.Eq(3*x + 2*y + 2*z, 2) 
eq3 = sp.Eq(x + y + z, 3)

# Coefficient matrix of the system
A = sp.Matrix([[2, 3, 1], [3, 2, 2], [1, 1, 1]])
# Free terms vector
b = sp.Matrix([1, 2, 3])
```

```{python}
A
```

```{python}
b
```

```{python}
# Define matrix A_1
A_1 = A.copy() # Copy matrix A
A_1[:, 0] = b # Replace the first column of A with vector b
A_1 # Check if the replacement was successful
```

```{python}
det_A_1 = A_1.det() # Calculate determinant of A_1
sol_x = det_A_1 / A.det() # Calculate x_1
sol_x # Calculated value of x_1
```

```{python}
# Similarly for y
A_2 = A.copy()
A_2[:, 1] = b
A_2 # Check if the replacement was successful
```

```{python}
det_A_2 = A_2.det()
sol_y = det_A_2 / A.det()
sol_y
```

```{python}
# Finally for z
A_3 = A.copy()
A_3[:, 2] = b
det_A_3 = A_3.det()
sol_z = det_A_3 / A.det()
sol_z
```

```{python}
# Solve the system of equations
sp.solve((eq1, eq2, eq3), (x, y, z))
```

---

## Exercises for Students

1. Solve the system of equations:
   $$
   \begin{cases}
   2x_1 - 3x_2 = 7 \\
   3x_1 + 5x_2 = 2
   \end{cases}
   $$

2. Solve the system of equations:
   $$
   \begin{cases}
   2x + y - z = 1 \\
   x - y + 2z = 4 \\
   3x - 2z = -1
   \end{cases}
   $$

3. Solve the system of equations:
   $$
   \begin{cases}
   x + y + z - t = 2 \\
   x - z + 2t = 6 \\
   2x - 3y + t = 4 \\
   3x + y + 3z - 4t = -2
   \end{cases}
   $$

4. Why can't the following system of equations be solved using Cramer's rule?
$$
\begin{cases}
x_1 + 2x_2 + 3x_3 = 3 \\
4x_1 + 5x_2 + 6x_3 = 2 \\
7x_1 + 8x_2 + 9x_3 = 1
\end{cases}
$$
