---
title: 'Wektory - Iloczyn skalarny, wektorowy, mieszany'
jupyter: python3
---




## Iloczyn skalarny

Iloczyn skalarny (zwany również iloczynem wewnętrznym) dwóch wektorów to operacja, która zwraca skalarną wartość. Jest definiowany jako suma iloczynów odpowiadających sobie współrzędnych dwóch wektorów.

Dla dwóch wektorów $\mathbf{a}$ i $\mathbf{b}$ w przestrzeni $\mathbb{R}^n$, gdzie:

$$
\mathbf{a} = [a_1, a_2, \dots, a_n], \quad \mathbf{b} = [b_1, b_2, \dots, b_n]
$$

Iloczyn skalarny definiuje się następująco:

$$
\mathbf{a} \cdot \mathbf{b} = a_1b_1 + a_2b_2 + \dots + a_nb_n = \sum_{i=1}^{n} a_i b_i
$$

Przykład dla przestrzeni trójwymiarowej ($ \mathbb{R}^3 $):

Dla wektorów $\mathbf{a} = [a_1, a_2, a_3]$ oraz $\mathbf{b} = [b_1, b_2, b_3]$, iloczyn skalarny to:

$$ 
\mathbf{a} \cdot \mathbf{b} = a_1b_1 + a_2b_2 + a_3b_3
$$

Iloczyn skalarny zwraca liczbę, która jest miarą "podobieństwa kierunku" dwóch wektorów. Jeśli $\mathbf{a} \cdot \mathbf{b} = 0$, to wektory są prostopadłe.

Alternatywnie, iloczyn skalarny można zapisać jako:

$$
\mathbf{a} \cdot \mathbf{b} = \|\mathbf{a}\| \|\mathbf{b}\| \cos(\theta),
$$
czyli iloczyn długości wektorów $\mathbf{a}$ i $\mathbf{b}$ pomnożony przez cosinus kąta między nimi.

## Iloczyn wektorowy

Iloczyn wektorowy (zwany również iloczynem zewnętrznym) to operacja, która zwraca nowy wektor prostopadły do dwóch wektorów wyjściowych. Jest zdefiniowany tylko w przestrzeni trójwymiarowej $ \mathbb{R}^3 $.

Dla dwóch wektorów $ \mathbf{a} = [a_1, a_2, a_3] $ oraz $ \mathbf{b} = [b_1, b_2, b_3] $, iloczyn wektorowy $ \mathbf{a} \times \mathbf{b} $ definiuje się jako:

$$ \mathbf{a} \times \mathbf{b} =
\begin{vmatrix}
\mathbf{i} & \mathbf{j} & \mathbf{k} \\
a_1 & a_2 & a_3 \\
b_1 & b_2 & b_3
\end{vmatrix}
$$

Gdzie $ \mathbf{i}, \mathbf{j}, \mathbf{k} $ to wektory jednostkowe wzdłuż osi $ x, y, z $. Dość zabawnie, aby policzyć iloczyny wektorowy i otrzymać finalny wektor używamy wyznacznika (skalara) z macierzy (tensor drugiego rzędu), wierszami której są wektory bazowe (wektory) i składowe wektorów (skalary).

Iloczyn wektorowy można zapisać w postaci rozwiniętej:

$$ \mathbf{a} \times \mathbf{b} = \left( a_2b_3 - a_3b_2 \right)\mathbf{i} - \left( a_1b_3 - a_3b_1 \right)\mathbf{j} + \left( a_1b_2 - a_2b_1 \right)\mathbf{k} $$

Wynikiem iloczynu wektorowego jest nowy wektor:

$$ \mathbf{c} = \mathbf{a} \times \mathbf{b} = [a_2b_3 - a_3b_2, a_3b_1 - a_1b_3, a_1b_2 - a_2b_1] $$

Iloczyn wektorowy zwraca wektor $\mathbf{c}$ prostopadły do płaszczyzny wyznaczonej przez $ \mathbf{a} $ i $ \mathbf{b} $, a jego długość jest równa powierzchni równoległoboku, którego boki są wyznaczone przez wektory $ \mathbf{a} $ i $ \mathbf{b} $
$$
|\mathbf{c}| = |\mathbf{a}| |\mathbf{b}| \sin \theta
$$

gdzie $\theta$ jest kątem między wektorami. Kierunek wektora $\vec{c}$ określa reguła prawej dłoni.

## Iloczyn mieszany

Iloczyn mieszany trzech wektorów $\mathbf{a}, \mathbf{b}, \mathbf{c}$ jest definiowany jako:

$$
\mathbf{a} \cdot \left( \mathbf{b} \times \mathbf{c} \right)
$$

Jest to równoważne iloczynowi skalarnemu $\mathbf{a} \times \left( \mathbf{b} \times \mathbf{c} \right)$.

Iloczyn mieszany jest równy zero, jeśli wektory $\mathbf{a}, \mathbf{b}, \mathbf{c}$ są współliniowe lub równoległe.

Objętość równoległościanu wyznaczonego przez trzy wektory $\mathbf{a}, \mathbf{b}, \mathbf{c}$ jest równa wartości bezwzględnej iloczynu mieszanej tych wektorów.

## Implementacja

```{python}
import sympy as sp 
# Definicje wektorów
a = sp.Matrix([1, 2, 3])
b = sp.Matrix([4, 5, 6])
c= sp.Matrix([7, 0, 9])
d= sp.Matrix([0, 2, 0])
```

```{python}
# wyświetlenie wektora c
c
```

```{python}
# dodawanie wektorów a i b
a+b
```

```{python}
# iloczyn skalarny a i b
(1*4+2*5+3*6)==a.dot(b)
```

```{python}
#iloczyn wektorowy a i c
# a = [1, 2, 3]
# c= [7, 0, 9]

# Pomocniczo zapiszmy wektory jako macierze 3x3
# i, j, k
# 1, 2, 3
# 7, 0, 9

# Teraz
comp1 = (2*9-3*0)
comp2 = -(1*9-3*7)
comp3 = (1*0-2*7)

# Wynik
sp.Matrix([comp1, comp2, comp3])==a.cross(c)
```

```{python}
# Prostopadłość wektorów
# c= [7, 0, 9]
# d= [0, 2, 0]

# Jeśli iloczyn skalarny wektorów jest równy 0, to znaczy, że są one prostopadłe
iloczyn_skalarny = 7*0+0*2+9*0
iloczyn_skalarny==0
```

## Zastosowania

### Obliczanie kąta między wektorami

$$
\cos \theta = \frac{\mathbf{a} \cdot \mathbf{b}}{\|\mathbf{a}\| \|\mathbf{b}\|}
$$

### Sprawdzanie prostopadłości wektorów

Wektory $\mathbf{a}$ i $\mathbf{b}$ są prostopadłe, jeśli ich iloczyn skalarny wynosi zero:
$$
\mathbf{a} \cdot \mathbf{b} = 0 
\quad \Leftrightarrow \quad
 \mathbf{a} \perp \mathbf{b}
$$

### Znajdowanie rzutów wektorów na inne wektory

$$
\text{Rzut} = \frac{\mathbf{a} \cdot \mathbf{b}}{\|\mathbf{b}\|}
$$

### Obliczanie pracy wykonanej przez siłę w fizyce

Dla siły $\mathbf{F} = (F_x, F_y, F_z)$ działającej wzdłuż przemieszczenia $\mathbf{d} = (d_x, d_y, d_z)$, praca obliczana jest zgodnie ze wzorem:

$$
W = \mathbf{F} \cdot \mathbf{d} = |\mathbf{F}| |\mathbf{d}| \cos \theta = F_x d_x + F_y d_y + F_z d_z
$$

### Moment siły

W fizyce: moment siły (moment obrotowy) to iloczyn wektorowy wektora siły i ramienia:

$$
\mathbf{M} = \mathbf{r} \times \mathbf{F}
$$

### Obliczanie pola równoległoboku

Pole równoległoboku rozpiętego na dwóch wektorach:

$$
\text{Area}_{r} = \mathbf{a} \times \mathbf{b} = |\mathbf{a}| |\mathbf{b}| \sin \theta
$$

### Obliczanie pola trójkąta

Pole trójkąta rozpiętego na dwóch wektorach $\mathbf{a}$ i $\mathbf{b}$:

$$
\text{Area}_{t} = \frac{1}{2} |\mathbf{a} \times \mathbf{b}|
$$

### Obliczanie objętości równoległościanów i czworościanów

Iloczyn mieszany wektorów jest używany do obliczania objętości równoległościanów i czworościanów. Dla trzech wektorów **$\mathbf{a}$**, **$\mathbf{b}$** i **$\mathbf{c}$**, objętość równoległościanu jest dana wzorem:

$$
V = |\mathbf{a} \cdot (\mathbf{b} \times \mathbf{c})|
$$
(Uwaga: **| |** oznacza tutaj wartość bezwzględną, a nie długość!)

### Sprawdzanie współpłaszczyznowości trzech wektorów

Jeśli iloczyn mieszany trzech wektorów jest równy zeru, oznacza to, że wektory są współpłaszczyznowe. W przeciwnym razie, tworzą one czworościan.

---

## Zadania dla studentów

A. Zrealizuj dodawanie wektora $[2, 1]$ do wektora $[-1, 1]$. Zaznacz oba wektory oraz ich sumę na wykresie.

B. Policz pole trójkąta rozpiętego na wektorach $[2, 1]$ i $[-1, 1]$.

C. Policz objętość równoległościanu rozpiętego na wektorach $[2, 1]$, $[-1, 1]$ i $[1, 2]$.

D. Sprawdź, czy wektory $[2, 1]$ i $[-1, 1]$ są prostopadłe.

E. Policz kąt w stopniach między wektorami $[4,2,1]$ a $[1,3,2]$.

F. Dla wektorów trójwymiarowych: $\mathbf{a}=[a_x, a_y, a_z]$, $\mathbf{b}=[b_x, b_y, b_z]$, $\mathbf{c}=[c_x, c_y, c_z]$, udowodnij, że spełniona jest tożsamość: 

$$
\mathbf{a} \times (\mathbf{b} \times \mathbf{c}) = (\mathbf{a} \cdot \mathbf{c}) \mathbf{b} - (\mathbf{a} \cdot \mathbf{b}) \mathbf{c}.
$$


